version: '3.4'

services:
  responderjs:
    image: responderjs
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9100:9229
    command: ["node", "--inspect=0.0.0.0:9229", "./src/responder.js"]
